env:
  NODE_VERSION: '16'
  PACT_BROKER_FEATURES: publish_pacts_using_old_api

BUILD_TEST_TASK_TEMPLATE: &BUILD_TEST_TASK_TEMPLATE
  arch_check_script:
    - uname -am
  test_script:
    - node --version
    - script/ci/build-and-test.sh

linux_arm64_task: 
  arm_container:
    image: node:$NODE_VERSION
    cpu: 4
    memory: 12G
  << : *BUILD_TEST_TASK_TEMPLATE

macosx_arm64_task: 
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  setup_script:
    - brew install nvm
    - source $(brew --prefix nvm)/nvm.sh
    - nvm install $NODE_VERSION
    - nvm use $NODE_VERSION
  << : *BUILD_TEST_TASK_TEMPLATE



